version: "3.8"
services:

  customer:
    build: ./customer
    container_name: omul_customer
    networks:
      - omul
    ports:
      - "8100:8080"
    environment:
      - CUSTOMER_DB_TYPE=mock
      - CUSTOMER_CACHE_ENABLED=false
      - CUSTOMER_JWT_ENABLED=false
      - CUSTOMER_TRANSPORT_TYPE=sync

  schedule:
    build: ./schedule
    container_name: omul_schedule
    networks:
      - omul
    ports:
      - "8101:8080"
    environment:
      - SCHEDULE_DB_TYPE=mock
      - SCHEDULE_CACHE_ENABLED=false
      - SCHEDULE_JWT_ENABLED=false
      - SCHEDULE_TRANSPORT_PERSONNEL_TYPE=mock

  personnel:
    build: ./personnel
    container_name: omul_personnel
    networks:
      - omul
    ports:
      - "8102:8080"
    environment:
      - PERSONNEL_DB_TYPE=mock
      - PERSONNEL_CACHE_ENABLED=false
      - PERSONNEL_JWT_ENABLED=false

  appointment:
    build: ./appointment
    container_name: omul_appointment
    networks:
      - omul
    ports:
      - "8103:8080"
    environment:
      - APPOINTMENT_DB_TYPE=mock
      - APPOINTMENT_CACHE_ENABLED=true
      - APPOINTMENT_CACHE_PROVIDER=inner
      - APPOINTMENT_JWT_ENABLED=false
      - APPOINTMENT_TRANSPORT_TYPE=sync
      - APPOINTMENT_TRANSPORT_CUSTOMER_TYPE=mock
      - APPOINTMENT_TRANSPORT_SCHEDULE_TYPE=mock

  auth:
    build: ./auth
    container_name: omul_auth
    networks:
      - omul
    ports:
      - "8105:8080"
    depends_on:
      - redis
    environment:
      - AUTH_DB_TYPE=mock
      - AUTH_CACHE_ENABLED=true
      - AUTH_CACHE_PROVIDER=redis
      - AUTH_CACHE_HOST=omul_redis

  redis:
    image: redis
    container_name: omul_redis
    networks:
      - omul
    ports:
      - "6379:6379"

networks:
  omul: