@startuml
skinparam {
    BackgroundColor lightGray
    ArrowColor darkblue
    ArrowThickness 2
    RoundCorner 10
    DefaultTextAlignment center
}

hide stereotype

<style>
 .block * {
     BackgroundColor lightGreen
     FontColor black
     RoundCorner 20
 }
.callStyle * {
  BackgroundColor lightYellow
  FontColor black
  RoundCorner 10
}
</style>

|Customer|
start
:Приходит на ресепшн;

|Administrator|
package "Регистрация визита" <<block>> {
    :Проверить корректность визита;
    if (Данные корректны?) is (Нет) then
        end
    endif
    if (Клиент пришел первый раз?) is (Да) then
        :Создать новый файл клиента;
        :Привязать данные визита в файл;
    else (Нет)
        :Найти карту клиента;
    endif
}

:Проводить клиента к врачу;
|Dentist|
:Провести обследования/лечение;
:Провести клиента на ресепшн;
:Описать проведенные процедуры, \n дальнейшее лечение;
|Administrator|
fork
    :Внести данные в \n мед.карту клиента;
fork again
    if (Назначены обследования?) is (Да) then
        :Выписать клиенту \n назначение на обследования;
    endif
    if (Назначено лечение?) is (Да) then
        :Просмотреть свободные слоты \n в расписании врачей;
        :Внести заявки в расписание;
    endif
end fork

package "Оплата" <<block>> {
    :Проверить в дисконтной системе, \n есть ли у клиента скидки, баллы;
    if (Есть скидка, клиент хочет применить?) is (Да) then
        :Внести скидку в протокол посещения;
    endif
    if (Есть баллы, клиент хочет оплатить?) is (Да) then
        :Внести баллы в протокол посещения;
    endif

    switch (Предложить варианты оплаты)
    case ( Наличными)
      :Произвести расчет;
      :Отметить вручную оплату \n в протоколе посещения;
    case ( Банковской картой)
      :Произвести расчет;
      :Убедиться об успешной отметке \n в протоколе посещения;
    case ( Оплата по \n выставленному счету)
      :Сформировать счет;
      : Отправить счет на \n электронную почту;
    endswitch
}
if (Распечатать документы клиенту?) is (Да) then
    :Распечатать необходимые документ, передать клиенту;
endif

stop

@enduml