apiVersion: v2
name: omul
description: Dental clinic

type: application
version: 0.0.2
appVersion: "0.0.2"

dependencies:
  - name: redis
    version: 18.14.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled